name: Deploy to Render

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Render
        uses: render-actions/deploy@v1
        with:
          service-id: https://progress-ytar.onrender.com
          api-key: ${{ secrets.RENDER_API_KEY }}
